package dk.easv.mytunes.GUI;

import dk.easv.mytunes.Be.Song;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.input.Dragboard;
import javafx.scene.input.TransferMode;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.Media;
import javafx.scene.text.Text;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.util.Duration;
import java.io.File;
import java.util.Arrays;
import java.util.List;

public class SongController {

    @FXML private Label lbWindowTitle;
    @FXML private Button btnBrowse;
    @FXML private Text txtErrorTitle;
    @FXML private Text txtErrorArtist;
    @FXML private Text txtErrorCategory;
    @FXML private Text txtErrorFile;
    @FXML private Text txtErrorLength;
    @FXML private TextField txtFTitle;
    @FXML private TextField txtFArtist;
    @FXML private ComboBox cbCategory;
    @FXML private TextField txtFTime;
    @FXML private TextField txtFileDrop;

    // Instance variables
    private MainController parent;
    private boolean editMode = false;
    private int editId;
    private File songFile;

    public void initialize() {
        generateCategories();

        txtFileDrop.setOnDragOver(event -> {
            if (event.getGestureSource() != txtFileDrop && event.getDragboard().hasFiles()) {
                event.acceptTransferModes(TransferMode.COPY_OR_MOVE);
            }
            event.consume();
        });

        txtFileDrop.setOnDragDropped(event -> {
            Dragboard db = event.getDragboard();
            boolean success = false;
            if (db.hasFiles()) {
                File file = db.getFiles().getFirst();
                if (file != null) {
                    String name = file.getName().toLowerCase();
                    if (name.endsWith(".mp3") || name.endsWith(".wav")) {
                        txtFileDrop.setText(file.getAbsolutePath());
                        songFile = file;
                        success = true;

                        autogenerateData(file);
                    }
                }
            }
            event.setDropCompleted(success);
            event.consume();
        });
    }

    private void generateCategories() {
        List<String> defaultCategories = Arrays.asList("","Pop","Rock","Classic","Dance","Blues","Rap");
        cbCategory.getItems().addAll(defaultCategories);
    }

    public void setupWindowMode() {
        if(editMode) {
            lbWindowTitle.setText("Edit Song");
            btnBrowse.setDisable(true);
            txtFileDrop.setDisable(true);
            txtFTime.setDisable(true);
        }
    }


    public void init(Song song) {
        if(editMode){
            txtFTitle.setText(song.getTitle());
            txtFArtist.setText(song.getArtist());
            cbCategory.setValue(song.getCategory());
            txtFTime.setText(song.getFormattedTime());
            editId = song.getId();
        }
    }

    public void setParent(MainController mainController) {
        this.parent = mainController;
    }

    public void setEditMode() {
        editMode = true;
    }

    public void onCancel(ActionEvent actionEvent) {
        closeWindow(actionEvent);
    }

    public void onSave(ActionEvent actionEvent) {
        if(checkDataValidation()){
            String timeAsString = txtFTime.getText();
            String[] timeParts = timeAsString.split("\\.");
            int timeInSeconds = Integer.parseInt(timeParts[0]) * 60 + Integer.parseInt(timeParts[1]);
            Song song;
            if(editMode){
                // Edit Mode.
                song = new Song(
                        editId,
                        txtFTitle.getText(),
                        txtFArtist.getText(),
                        cbCategory.getValue().toString(),
                        songFile,
                        timeInSeconds);
                parent.updateSong(song);
            } else {
                // Create new song.
                song = new Song(
                        txtFTitle.getText(),
                        txtFArtist.getText(),
                        cbCategory.getValue().toString(),
                        songFile,
                        timeInSeconds
                );
                parent.createSong(song);
            }
            closeWindow(actionEvent);
        }
    }

    private boolean checkDataValidation() {
        boolean valid = true;

        boolean isTitleValid = validateField(txtFTitle.getText());
        txtErrorTitle.setVisible(!isTitleValid);
        valid &= isTitleValid;

        boolean isArtistValid = validateField(txtFArtist.getText());
        txtErrorArtist.setVisible(!isArtistValid);
        valid &= isArtistValid;

        boolean isCategoryValid = cbCategory.getValue() != null && validateField(cbCategory.getValue().toString());
        txtErrorCategory.setVisible(!isCategoryValid);
        valid &= isCategoryValid;

        boolean isTimeValid = validateField(txtFTime.getText());
        txtErrorLength.setVisible(!isTimeValid);
        valid &= isTimeValid;

        boolean isFileValid = editMode || validateField(txtFileDrop.getText());
        txtErrorFile.setVisible(!isFileValid);
        valid &= isFileValid;

        return valid;
    }

    private boolean validateField(String fieldText){
        return !fieldText.isEmpty();
    }

    private void autogenerateData(File file) {
        if (txtFTitle.getText().isEmpty())
            autogenerateTitle(file);
        autogenerateTime(file);
    }

    private void autogenerateTitle(File file) {
            String title = file.getName().replace(".mp3", "");
            title = title.replace(".wav", "");
            txtFTitle.setText(title);
    }

    private void autogenerateTime(File file) {
        Media media = new Media(file.toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(media);

        mediaPlayer.setOnReady(() -> {
            Duration duration = media.getDuration();
            double seconds = duration.toSeconds();

            int minutes = (int) seconds / 60;
            int secs = (int) seconds % 60;

            txtFTime.setText(minutes + "." + String.format("%02d", secs));
        });
    }

    public void closeWindow(ActionEvent actionEvent){
        Button btn = (Button) actionEvent.getSource();
        Stage window = (Stage) btn.getScene().getWindow();
        window.close();
    }

    @FXML private void onBrowseFile(ActionEvent actionEvent) {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Choose a music file");
        Button source = (Button) actionEvent.getSource();

        Stage stage = (Stage) source.getScene().getWindow();
        File file = fileChooser.showOpenDialog(stage);
        if(file != null) {
            String filepath = String.valueOf(file);
            txtFileDrop.setText(filepath);
            autogenerateData(file);
        }
    }
}
