package dk.easv.mytunes.GUI;

import dk.easv.mytunes.Be.Song;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.scene.input.Dragboard;
import javafx.scene.input.TransferMode;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.Media;
import javafx.stage.Stage;
import javafx.util.Duration;

import java.io.File;

public class SongController {

    @FXML private TextField txtFTitle;
    @FXML private TextField txtFArtist;
    @FXML private ComboBox cbCategory;
    @FXML private TextField txtFTime;
    @FXML private TextField txtFileDrop;

    private MainController parent;
    private boolean editMode = false;
    private int editId;
    private File songFile;

    public void initialize() {
        txtFileDrop.setPromptText("Drop an MP3 or WAV file here");
        txtFileDrop.setEditable(false);

        txtFileDrop.setOnDragOver(event -> {
            if (event.getGestureSource() != txtFileDrop && event.getDragboard().hasFiles()) {
                event.acceptTransferModes(TransferMode.COPY_OR_MOVE);
            }
            event.consume();
        });

        txtFileDrop.setOnDragDropped(event -> {
            Dragboard db = event.getDragboard();
            boolean success = false;
            if (db.hasFiles()) {
                File file = db.getFiles().getFirst();
                if (file != null) {
                    String name = file.getName().toLowerCase();
                    if (name.endsWith(".mp3") || name.endsWith(".wav")) {
                        txtFileDrop.setText(file.getAbsolutePath());
                        songFile = file;
                        success = true;

                        autogenerateData(file);
                    }
                }
            }
            event.setDropCompleted(success);
            event.consume();
        });
    }


    public void init(Song song) {
        if(editMode){
            txtFTitle.setText(song.getTitle());
            txtFArtist.setText(song.getArtist());
            cbCategory.setValue(song.getCategory());
            txtFTime.setText(song.getFormattedTime());
            editId = song.getId();
        }
    }

    public void setParent(MainController mainController) {
        this.parent = mainController;
    }

    public void setEditMode() {
        editMode = true;
    }

    public void onCancel(ActionEvent actionEvent) {
        closeWindow(actionEvent);
    }

    public void onSave(ActionEvent actionEvent) {
        if(editMode){
            // Edit Mode.
            String timeAsString = txtFTime.getText();
            String[] timeParts = timeAsString.split("\\.");
            int timeInSeconds = Integer.parseInt(timeParts[0]) * 60 + Integer.parseInt(timeParts[1]);
            Song song = new Song(editId, txtFTitle.getText(), txtFArtist.getText(), cbCategory.getValue().toString(), timeInSeconds);
            if(songFile != null) {
                song.setFile(songFile);
            }
            parent.updateSong(song);
        } else {
            // Create new song.
            String timeAsString = txtFTime.getText();
            String[] timeParts = timeAsString.split("\\.");
            int timeInSeconds = Integer.parseInt(timeParts[0]) * 60 + Integer.parseInt(timeParts[1]);

            Song newSong = new Song(
                    txtFTitle.getText(),
                    txtFArtist.getText(),
                    cbCategory.getValue().toString(),
                    timeInSeconds
            );
            if(songFile != null) {
                newSong.setFile(songFile);
            }
            parent.createSong(newSong);
        }
        closeWindow(actionEvent);
    }

    private void autogenerateData(File file) {
        String title = file.getName().replace(".mp3", "");
        title = title.replace(".wav", "");
        txtFTitle.setText(title);

        Media media = new Media(file.toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(media);

        mediaPlayer.setOnReady(() -> {
            Duration duration = media.getDuration();
            double seconds = duration.toSeconds();

            int minutes = (int) seconds / 60;
            int secs = (int) seconds % 60;

            txtFTime.setText(minutes + ":" + String.format("%02d", secs));
        });
    }

    public void closeWindow(ActionEvent actionEvent){
        Button btn = (Button) actionEvent.getSource();
        Stage window = (Stage) btn.getScene().getWindow();
        window.close();
    }
}
